core-webapp/src/main/java/no/arkivlab/hioa/nikita/webapp/model/application/CaseHandlingDetails.java, core-webapp/src/main/java/no/arkivlab/hioa/nikita/webapp/model/application/FondsStructureDetails.java
This bring the implementation in line with the relation key tables in the
specification but make the behaviour different from the output from the
demo site provided by the specification writers.
=> Use trailing slash on all relation key URLs.

Makefile
While the maven commands are simple to use, they are hard to remember
IMO. Running just `make` is nicer and shorter. The Makefile could be
used to capture tedious repetitive tasks.  For now I have just added two
recipes the default target `make` will try to build and run. `make es`
should spin up a elasticsearch container.
=> use a Makefile to ease getting up and running

Dockerfile, Makefile
By using docker[0] we can make it very easy for someone who is interested in
spinning up a new instance to get started. Instead of installing all of the
dependencies and going through the hassle of having the right versions,
requiring only one command like `make docker_run` is a much better experience.
For now the container is cloning the source so it's less focused on using the
local files. This can be changed if there is a strong need for making it easier
to test the local changes, but it would require some more thought.
Some changes were made to the Makefile. The name field is now being set for the
elasticsearch container which makes it easier to use with other containers via
the `--link` option and we have four more targets[1] to the Makefile. The
targets are there primarily so people …
=> add a dockerfile

Makefile
While it add comments and handle known issues when using elasticsearch.  This
should also address some hibernate boot exceptions.
Reference:
o https://github.com/docker-library/elasticsearch/issues/58
o https://github.com/HiOA-ABI/nikita-noark5-core/blob/master/0.2-release/elasticsearch.txt
=> Fix connection issues when using `make es` and `make run`

Makefile
The repo_* variables have default values but could be changed out.  In
order to make it more user friendly the repository is cloned if it
doesn't exist.
References:
https://github.com/petterreinholdtsen/noark5-tester/issues/1#issuecomment-281139379
[0]: https://github.com/petterreinholdtsen/noark5-tester
=> Makefile: add new target to use noark5-tester[0]

Makefile
This fixes a compile errors which only shows up after cleaning the
project and then attempting packaging it.
=> Makefile: package target should depend on build

.gitignore, Vagrantfile, install-deps-debian.sh
Vagrant[0] makes it easier to create a reproducible environment and can
potentially help new people to get a environment up and running by. This
setup uses the upsteam version of docker and it also adds the vagrant
user to the docker group while not required but for debug nice to have
access to docker. The vm should have everything you need including
elasticsearch and various dependencies required to run the application.
Using this should look something like:
```shell
vagrant up
vagrant ssh
cd /vagrant && make run
```
Later when you have changes:
```shell
vagrant reload
```
This is also something we could use with some continuous integration.
Not sure about travis, but Jenkins has a plugin[1] which might be
useful.
Please note that docker is not included in install-deps-debian.sh so
that …
=> Add support for Vagrant

Makefile
For some reason I couldn't register hioa-abi. I suspect dashes are not
allowed, but there does not seem to be any information on this from
docker[0]. The project name can be changed, I just wanted to use
something valid to upload to for now.
Also added the full docker hub URL to the output.
[0]: https://github.com/docker/hub-feedback/issues/158
=> Makefile: change project name variable

core-webapp/src/main/java/no/arkivlab/hioa/nikita/webapp/spring/AppWebMvcConfiguration.java
Turns out the IDE is doing some magic in the background and strips away
preceded slashes. This is not the case for the jar and we get the mapping
errors below.
2017-02-23 23:24:56.491 ERROR 1 --- [0.1-8092-exec-5] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-127.0.0.1-8092-exec-5] Exception processing template "/webapp/login/loginPage": Error resolving template "/webapp/login/loginPage", template might not exist or migh
t not be accessible by any of the configured Template Resolvers
2017-02-23 23:24:56.492 ERROR 1 --- [0.1-8092-exec-5] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/noark5v4] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInput …
=> Fix mapping error when using jar file with Thymeleaf

Makefile
This let's you run deploy on a empty build so you have the jar needed by the
builder.  Fixes the following issue:
docker build -t nikita5/nikita-noark5-core .
Sending build context to Docker daemon 138.1 MB
Step 1/6 : FROM java:8
---> d23bdf5b1b1b
Step 2/6 : VOLUME /tmp
---> Using cache
---> ccf7b0663c61
Step 3/6 : ADD core-webapp/target/core-webapp-0.1.0-spring-boot.jar app.jar
lstat core-webapp/target/core-webapp-0.1.0-spring-boot.jar: no such file or director
=> Makefile: let docker_run depend on build and package target

Install.md
While nice to build it is already covered by the Makefile, the two
remaining commands is the minimum required to spin up the application.
=> Install: remove build line for docker setup

Makefile
Fixes the following error:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'startDBManager' defined in
no.arkivlab.hioa.nikita.webapp.spring.datasource.DemoDataSource: Bean instantiation via factory method failed; nested exception is
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.h2.tools.Server]: Factory method 'startDBManager' threw exception; nested
exception is org.h2.jdbc.JdbcSQLException: IO Exception: "java.net.UnknownHostException: moby: moby: Name or service not known" [90028-190]
Reference:
http://blog.yohanliyanage.com/2016/09/docker-machine-moby-name-or-service-not-known/
=> Makefile: add moby host

Makefile
Running it this way gives us the application output.
Which turns out to be needed most of the times.
=> Makefile: remove extra options in docker_run

Install.md, Makefile
The previous moby fix will only work on a docker machine for macOS.
Using the hostname is more reliable.
=> Makefile: Install: use variable host

Makefile, docker-compose.yml
Compose[0] let's us define and run multiple containers with docker.
```bash
root@ip-172-31-21-156:/home/ubuntu/src/nikita-noark5-core# docker-compose up # or make docker_compose
Creating network "nikitanoark5core_default" with the default driver
Pulling elasticsearch (elasticsearch:2.4.4)...
2.4.4: Pulling from library/elasticsearch
5040bd298390: Pull complete
fce5728aad85: Pull complete
c42794440453: Pull complete
0c0da797ba48: Pull complete
7c9b17433752: Pull complete
d4d33418bd6d: Pull complete
0e10cce36e52: Pull complete
09dd4de551b0: Pull complete
dd2fffb2567d: Pull complete
00600327a779: Pull complete
fae2df12d2f6: Pull complete
f60afcfaf7ae: Pull complete
7054ec74e0a2: Pull complete
4c5d3a9e8b2a: Pull complete
Digest: sha256:c977957d91c253eff6ea19f0501a2b2ae39a06e8e10d9adf5404a9fd62 …
```
=> Makefile: Add docker compose target

Dockerfile
This makes the container buildable from docker hub. We do lose the
option to test local wars, but pushing your branch to github and
changing the environment's should not be that hard.
Also tried to slim down apt cache.
=> Dockerfile: use github

Dockerfile
This should prevent java version mismatches error below and also reduces the
image size from 623MB to 440MB. It's still not around 300MB we had before
aaf6e20f9b02 (Dockerfile: use github, 2017-02-25), but reducing the size even
more can be done later. We are now using the `mvn` command directly so the
container does not need to install `make`.
Also added comments to the Dockerfile.  Hopefully this makes the file
more obvious for new docker users.
docker run --network="host" --add-host=hafza.local:127.0.0.1 nikita5/nikita-noark5-core
Exception in thread "main" java.lang.UnsupportedClassVersionError: no/arkivlab/hioa/nikita/webapp/run/N5CoreApp : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at …
=> Dockerfile: fix java version mismatch by using maven image

Install.md
In order to make avoid the HSEARCH400024 which is already documented.
We need to figure out how to fix this for the docker-compose...
=> Install: make the Docker section more copy / paste friendly

Makefile
This commit was needed earlier but because we changed the way the Docker
container is being built this is no longer needed and is only incurring
unnecessary build time.
This reverts commit 6e5fdfa38936ee82d2657dc0d78e0e08768c9316.
=> Revert "Makefile: let docker_run depend on build and package target"

docs/general/Install.md
While not essential there, is nice to be able to copy
all the lines and just run them.
=> docs: add noark5-tester container run to Install

web/README.md
When re basing earlier, I must have missed that the port should be 3000
not 4200 from angular-cli.
=> web/README: fix port typo

docs/general/Install.md, scripts/start-containers
Instead of duplicating lines just use the script the install
instructions as well. This script can be used to setup staging server
for prototyping.
=> scripts: docs: use a separate script for spinning up containers

scripts/start-containers
User should not have to deal with this, so script
should check for Darwin.
=> scripts: handle the moby hostname for macOS

Makefile, docs/general/Install.md
Experienced the error below, letting vagrant update the
box first fixes the issue.
...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
apt-get -y update
...
=> Makefile: add vagrant target

Makefile, docker-compose.yml, scripts/start-containers
I created new organization[0] which is connected to the Github repository.
While there is nothing wrong with using nikita5 it is incurring extra work on my
part to make sure the nikita5 fork is up to date. By using autobuild on the main
repository we can get latest changes sooner instead of waiting for me to
manually refresh my fork in order to trigger a rebuild.
[0]: https://hub.docker.com/r/hioaabi/nikita-noark5-core/
=> use hioaabi for nikita-noark5-core image

web/Makefile
The target should help Debian people avoid using npm, and maybe ease
potential future packaging efforts. Unfortunately getmdl does not have
Debian package (based on some minutes of searching). So therefore we
just download the files needed for now.
=> web/Makefile: add targets for Debian users

.travis.yml, scripts/run-all-tests
Just starting the containers is not enough and using a separate
script let's us extend the runner with more tests in the future.
Also added todo for replacing the call to start-containers with
actually building the container so we test local changes not just
latest changes.
=> build: use dedicated script for running tests

scripts/ci-test-runner, scripts/run-all-tests
As mentioned in b13561665a38 (build: use dedicated script for running
tests, 2017-03-31) we are not doing a realistic test of the pull
requests. This patch fixes that by building the image and running it.
=> build: let travis build the new container from local changes

.travis.yml
The IRC channel is becoming a center of communication for the project, send the
build notifications there so users don't need to check Github for latest status.
=> build: send notifications when done

Makefile
This should make running docker_run succeed in most if not all cases. With the
previous setup there where some ways you could trigger build errors because of
starting things in the wrong order and not waiting the minimum required time.
=> Makefile: let docker_run depend on es

core-common/src/main/java/nikita/config/N5ResourceMappings.java
The space made it impossible to add the field to the object during creation.
=> Remove trailing space from DOCUMENT_OBJECT_CHECKSUM_ALGORITHM.
